### PR TITLE
Temporarily remove @piecuu from webring

### PR DESCRIPTION
**Pull request by Piecuuu**
Server room flooded, had to evacuate servers. The PR could also not be pulled in, but then it would hurt the guests clicking next/random on sites and mine not loading. I'm aiming to get back online in a couple of days.

### CODE REVIEW

**Comment by jacekpoz** [comment]
good luck with the room!!!

**Comment by piecuu** [comment]
@Piecuuu wtf is going on here?

**Comment by Piecuuu** [comment]
> wtf is going on here?

Whoopsies, thats the Discord username I have and I pinged you by mistake. Sorry!

**Comment by piecuu** [comment]
> > wtf is going on here?
> 
> Whoopsies, thats the Discord username I have and I pinged you by mistake. Sorry!

no worries! anyway there can't be two of us with the same nickname, so I have to challenge you to a fight haha

**Comment by MicroPanda123** [comment]
@Piecuuu good luck with ur room

**Comment by Piecuuu** [comment]
> > > wtf is going on here?
> > 
> > Whoopsies, thats the Discord username I have and I pinged you by mistake. Sorry!
> 
> no worries! anyway there can't be two of us with the same nickname, so I have to challenge you to a fight haha

who's the impostor?

**Pull request merged**
