### PR TITLE
Add `cutedog5695` in webring.nix

### PR DESCRIPTION
**Pull request by CuteDog5695**
Not sure if this will get merged since my config is just configuration.nix but its worth a shot.

### CODE REVIEW

**Comment by jacekpoz** [comment]
linking your config is optional, what counts is that you're passionate about nix and have a personal website

**Comment by jacekpoz** [comment]
welcome!!

**Comment by jacekpoz** [comment]
ok one small issue can you remove the `target="_blank"`? I don't want any sites in the ring to stay open when browsing it, I want it all contained within a single tab

**Comment by CuteDog5695** [comment]
Ye sure, I can remove it

**Comment by jacekpoz** [comment]
thank you!

**Pull request merged**
