### PR TITLE
haiii :33333

### PR DESCRIPTION
**Pull request by Piecuuu**

### CODE REVIEW

**Comment by jacekpoz** [comment]
gonna wait for you to actually put something on your site

**Review by jacekpoz — CHANGES_REQUESTED** [review]
no no no no no, rebase your branch on top of main, then add yourself *at the bottom* of the list

**Comment by Jappie3** [comment]
no skipping the line! >:(

**Comment by jacekpoz** [comment]
image

**Comment by jacekpoz** [comment]
@Piecuuu small guide on this, I'll probably add something on the site at some point

remove all the commits you made by `git reset --soft <commit>`, `<commit>` being the one before your first one

then make sure your branch is up to date with the main one, whatever way you'd wanna do that

make your desired changes (add yourself *at the end* of the list), commit as usual and `git push --force` to forcefully overwrite all the changes you made on this branch so far

if you get stuck at any point don't hesitate to ask for help

**Pull request closed without merging**
